language: generic
sudo: required
servies:
  - docker

before_install:
  - docker build -t donfranquito/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true donfranquito/docker-react npm run test